---
#- name: Enable BGP Feature
#  hosts: switches
#  connection: local
#  tasks: 
#    - name: Enable BGP Feature
#      nxos_feature: 
#        host: "{{ inventory_hostname }}"
#        transport: nxapi
#        feature: bgp
#        state: enabled

- name: Setup BGP on Switches
  hosts: switches
  connection: local
  tasks: 
    - name: Configure BGP 
      nxos_bgp:
        host: "{{ inventory_hostname }}"
        transport: nxapi 
        asn: "{{ bgp.asn }}"
        vrf: default
        router_id: "{{ bgp.router_id }}"
        state: present
    - name: Configure Neighbors
      with_items: "{{ bgp.neighbors }}"
      nxos_bgp_neighbor: 
        host: "{{ inventory_hostname }}"
        transport: nxapi 
        asn: "{{ bgp.asn }}"
        neighbor: "{{ item.neighbor }}"
        remote_as: "{{ item.asn }}"
        description: "{{ item.description }}" 
        update_source: "{{ item.update_source }}"
        state: present
    - name: Configure Neighbors ipv4 Address Family
      with_items: "{{ bgp.neighbors }}"
      nxos_bgp_neighbor_af: 
        host: "{{ inventory_hostname }}"
        transport: nxapi 
        asn: "{{ bgp.asn }}"
        neighbor: "{{ item.neighbor }}"
        afi: ipv4
        safi: unicast
        state: present
    - name: Configure Default ipv4 Address Family
      nxos_bgp_af: 
        host: "{{ inventory_hostname }}"
        transport: nxapi 
        asn: "{{ bgp.asn }}"
        vrf: default
        afi: ipv4
        safi: unicast
        state: present
        networks: "{{ bgp.networks }}"
        
    