---
- name: Enable OSPF Feature
  hosts: switches
  connection: local
  tasks: 
    - name: Disable OSPF Feature
      nxos_feature: 
        host: "{{ inventory_hostname }}"
        transport: nxapi
        feature: ospf
        state: disabled
