---
- name: Configure IP Connectivity for L3 Fabric
  hosts: switches
  connection: local
  tasks:
    - name: Set Interfaces for L3 Mode and Description
      with_items: "{{ l3_fabric.interfaces }}"
      nxos_interface:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        interface: "{{ item.name }}"
        mode: layer3
        description: "{{ item.desc }}"
        admin_state: up
    - name: Configure IPv4 Address on Interface
      with_items: "{{ l3_fabric.interfaces }}"
      nxos_ip_interface:
        host: "{{ inventory_hostname }}"
        state: present
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        interface: "{{ item.name }}"
        version: v4
        addr: "{{ item.ip_address }}"
        mask: "{{ item.prefix }}"
