---
- name: Enable OSPF Feature
  hosts: switches
  connection: local
  tasks:
    - name: Enable OSPF Feature
      nxos_feature:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        feature: ospf
        state: enabled

- name: Setup OSPF on Distribution Switches
  hosts: switches
  connection: local
  tasks:
    - name: Configure OSPF
      nxos_ospf:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        ospf: "{{ ospf.process }}"
        state: present
    - name: Enable OSPF on Interswitch Links
      with_items: "{{ l3_fabric.interfaces }}"
      nxos_interface_ospf:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        interface: "{{ item.name }}"
        ospf: "{{ ospf.process }}"
        area: "{{ ospf.area }}"
        passive_interface: false
    - name: Enable OSPF on Loopback Interfaces Links
      with_items: "{{ local_loopbacks }}"
      nxos_interface_ospf:
        host: "{{ inventory_hostname }}"
        transport: nxapi
        use_ssl: yes
        validate_certs: no
        interface: "{{ item.name }}"
        ospf: "{{ ospf.process }}"
        area: "{{ ospf.area }}"
        passive_interface: false
